server:
  port: 8080

spring:
  application:
    name: api-gateway-xetax

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          httpclient:
            connect-timeout: 5000
            response-timeout: 30s

          routes:

            - id: auth-service
              uri: lb://Authentication-XETAX
              predicates:
                - Path=/auth/**

            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/ai/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: YOUR_SUPER_SECRET_KEY_MINIMUM_32_CHARACTERS
    issuer: xetax

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    com.example.API_Gateway_XetaX: DEBUG